### ISSUE TITLE
Remove necessity to do file IO in conversion of surface mesh to libigl 

### ISSUE THREAD

**Issue by helen-brooks** [aurora-multiphysics/VacuumMesher#1]
Currently, before tetrahedralisation occurs, it is necessary to output the surface mesh (produced by skinning) to file. It would be good to eliminate this step. Writing to file should be an option as it is still useful for debugging.

Before doing this, add CI ensure good test coverage.

**Comment by TheBEllis** [comment]
Should have closed this one a while ago, methods to transfer libIGL meshes to libmesh meshes in memory have been working well!
