### ISSUE TITLE
Weird behaviour on sidesets

### ISSUE THREAD

**Issue by makeclean** [aurora-multiphysics/VacuumMesher#10]
In one of my problems, it seems that the side set for the part_boundary, which I think VacuumMesher creates - seems to be hardcoded to sideset 5? It wiped out one of my existing side sets, suggest this is unwanted behaviour and likely better to grab the next available sideset id

**Comment by TheBEllis** [comment]
Fixed in 44d4f01a91a915ec31e3e7401fbef43e6936a7cd :)
